package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Branch generated by hbm2java
 */
public class Branch extends BaseDomain implements java.io.Serializable {

	public static int OBJECTTYPEID = 2;
	public static String OBJECTTYPESTR = "Branch";
	
	private int branchId;
	private int organizationId;
	private String branchName;
	private String branchShortName;
	private String branchCode;
	private String businessRegistrationNumber;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date businessRegisteredDate;
	private Integer businessIncorporatedIn;
	private String primaryContact;
	private String weekDayStartAt;
	private String weekDayEndBy;
	private String weedEndStartAt;
	private String weekEndEndBy;
	private String remarks;
	private boolean letterHeadRequired;
	private boolean taxApplicable;
	private String taxRegistrationNumber;
	private Integer defaultCurrency;
	//Trade Receivable
	private String accountCode;
	private boolean brnEntityStatus;
	private byte[] logo;
	private String warehouseCode;
	private String commPort;
	private String healthcareEstablishmentCode;
	private String hospitalCode;
	private Integer defaultDoctorId;
	private Integer defaultLabId;
	private String labCentreCode;
	
	public Branch() {
	}

	public Branch(int branchId, int organizationId, String branchName,
			String branchShortName, String branchCode, boolean letterHeadRequired,
			int createdBy, Date createdDate, int lastUpdatedBy,
			Date lastUpdatedDate) {
		this.branchId = branchId;
		this.organizationId = organizationId;
		this.branchName = branchName;
		this.branchShortName = branchShortName;
		this.branchCode = branchCode;
		this.letterHeadRequired = letterHeadRequired;
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public Branch(int branchId, int organizationId, String branchName,
			String branchShortName, String branchCode,
			String businessRegistrationNumber, Date businessRegisteredDate,
			Integer businessIncorporatedIn, String primaryContact,
			String weekDayStartAt, String weekDayEndBy, String weedEndStartAt,
			String weekEndEndBy, String remarks, boolean letterHeadRequired,
			boolean taxApplicable, String taxRegistrationNumber,
			Integer defaultCurrency, boolean entityStatus, int createdBy,
			Date createdDate, int lastUpdatedBy, Date lastUpdatedDate,
			String healthcareEstablishmentCode, String hospitalCode,
			Integer defaultLab) {
		this.branchId = branchId;
		this.organizationId = organizationId;
		this.branchName = branchName;
		this.branchShortName = branchShortName;
		this.branchCode = branchCode;
		this.businessRegistrationNumber = businessRegistrationNumber;
		this.businessRegisteredDate = businessRegisteredDate;
		this.businessIncorporatedIn = businessIncorporatedIn;
		this.primaryContact = primaryContact;
		this.weekDayStartAt = weekDayStartAt;
		this.weekDayEndBy = weekDayEndBy;
		this.weedEndStartAt = weedEndStartAt;
		this.weekEndEndBy = weekEndEndBy;
		this.remarks = remarks;
		this.letterHeadRequired = letterHeadRequired;
		this.taxApplicable = taxApplicable;
		this.taxRegistrationNumber = taxRegistrationNumber;
		this.defaultCurrency = defaultCurrency;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
		this.healthcareEstablishmentCode = healthcareEstablishmentCode;
		this.hospitalCode = hospitalCode;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getBranchShortName() {
		return this.branchShortName;
	}

	public void setBranchShortName(String branchShortName) {
		this.branchShortName = branchShortName;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getBusinessRegistrationNumber() {
		return this.businessRegistrationNumber;
	}

	public void setBusinessRegistrationNumber(String businessRegistrationNumber) {
		this.businessRegistrationNumber = businessRegistrationNumber;
	}

	public Date getBusinessRegisteredDate() {
		return this.businessRegisteredDate;
	}

	public void setBusinessRegisteredDate(Date businessRegisteredDate) {
		this.businessRegisteredDate = businessRegisteredDate;
	}

	public Integer getBusinessIncorporatedIn() {
		return this.businessIncorporatedIn;
	}

	public void setBusinessIncorporatedIn(Integer businessIncorporatedIn) {
		this.businessIncorporatedIn = businessIncorporatedIn;
	}

	public String getPrimaryContact() {
		return this.primaryContact;
	}

	public void setPrimaryContact(String primaryContact) {
		this.primaryContact = primaryContact;
	}

	public String getWeekDayStartAt() {
		return this.weekDayStartAt;
	}

	public void setWeekDayStartAt(String weekDayStartAt) {
		this.weekDayStartAt = weekDayStartAt;
	}

	public String getWeekDayEndBy() {
		return this.weekDayEndBy;
	}

	public void setWeekDayEndBy(String weekDayEndBy) {
		this.weekDayEndBy = weekDayEndBy;
	}

	public String getWeedEndStartAt() {
		return this.weedEndStartAt;
	}

	public void setWeedEndStartAt(String weedEndStartAt) {
		this.weedEndStartAt = weedEndStartAt;
	}

	public String getWeekEndEndBy() {
		return this.weekEndEndBy;
	}

	public void setWeekEndEndBy(String weekEndEndBy) {
		this.weekEndEndBy = weekEndEndBy;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public boolean getLetterHeadRequired() {
		return this.letterHeadRequired;
	}

	public void setLetterHeadRequired(boolean letterHeadRequired) {
		this.letterHeadRequired = letterHeadRequired;
	}

	public byte[] getLogo() {
		return logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public boolean getTaxApplicable() {
		return this.taxApplicable;
	}

	public void setTaxApplicable(boolean taxApplicable) {
		this.taxApplicable = taxApplicable;
	}

	public String getTaxRegistrationNumber() {
		return this.taxRegistrationNumber;
	}

	public void setTaxRegistrationNumber(String taxRegistrationNumber) {
		this.taxRegistrationNumber = taxRegistrationNumber;
	}

	public Integer getDefaultCurrency() {
		return this.defaultCurrency;
	}

	public void setDefaultCurrency(Integer defaultCurrency) {
		this.defaultCurrency = defaultCurrency;
	}

	public int getObjectTypeId() {
		return OBJECTTYPEID;
	}

	public String getObjectTypeStr() {
		return OBJECTTYPESTR;
	}

	//Trade Receivable
	public String getAccountCode() {
		return accountCode;
	}

	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	public String getWarehouseCode() {
		return warehouseCode;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	public String getCommPort() {
		return commPort;
	}

	public void setCommPort(String commPort) {
		this.commPort = commPort;
	}

	public String getHealthcareEstablishmentCode() {
		return healthcareEstablishmentCode;
	}

	public void setHealthcareEstablishmentCode(String healthcareEstablishmentCode) {
		this.healthcareEstablishmentCode = healthcareEstablishmentCode;
	}

	public String getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode;
	}

	public boolean isBrnEntityStatus() {
		return brnEntityStatus;
	}

	public void setBrnEntityStatus(boolean brnEntityStatus) {
		this.brnEntityStatus = brnEntityStatus;
	}

	public Integer getDefaultDoctorId() {
		return defaultDoctorId;
	}

	public void setDefaultDoctorId(Integer defaultDoctorId) {
		this.defaultDoctorId = defaultDoctorId;
	}

	public Integer getDefaultLabId() {
		return defaultLabId;
	}

	public void setDefaultLabId(Integer defaultLabId) {
		this.defaultLabId = defaultLabId;
	}

	public String getLabCentreCode() {
		return labCentreCode;
	}

	public void setLabCentreCode(String labCentreCode) {
		this.labCentreCode = labCentreCode;
	}
}
