package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ContactInfo generated by hbm2java
 */
public class ContactInfo extends BaseDomain implements java.io.Serializable {

	public static int OBJECTTYPE = 20;
	public static String OBJECTTYPESTR = "ContactInfo";
	
	private int contactInfoId;
	private int organizationId;
	private int masterTypeId;
	private int masterId;
	private int contactTypeId;
	private String contactDetail;
	private String remarks;

	public ContactInfo() {
	}

	public ContactInfo(int contactInfoId, int crganizationId, int masterTypeId,
			int masterId, int contactTypeId, String contactDetail,
			boolean entityStatus, int createdBy, Date createdDate,
			int lastUpdatedBy, Date lastUpdatedDate) {
		this.contactInfoId = contactInfoId;
		this.organizationId = crganizationId;
		this.masterTypeId = masterTypeId;
		this.masterId = masterId;
		this.contactTypeId = contactTypeId;
		this.contactDetail = contactDetail;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public ContactInfo(int contactInfoId, int crganizationId, int masterTypeId,
			int masterId, int contactTypeId, String contactDetail,
			String remarks, boolean entityStatus, int createdBy,
			Date createdDate, int lastUpdatedBy, Date lastUpdatedDate) {
		this.contactInfoId = contactInfoId;
		this.organizationId = crganizationId;
		this.masterTypeId = masterTypeId;
		this.masterId = masterId;
		this.contactTypeId = contactTypeId;
		this.contactDetail = contactDetail;
		this.remarks = remarks;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public int getContactInfoId() {
		return this.contactInfoId;
	}

	public void setContactInfoId(int contactInfoId) {
		this.contactInfoId = contactInfoId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public int getMasterTypeId() {
		return this.masterTypeId;
	}

	public void setMasterTypeId(int masterTypeId) {
		this.masterTypeId = masterTypeId;
	}

	public int getMasterId() {
		return this.masterId;
	}

	public void setMasterId(int masterId) {
		this.masterId = masterId;
	}

	public int getContactTypeId() {
		return this.contactTypeId;
	}

	public void setContactTypeId(int contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	public String getContactDetail() {
		return this.contactDetail;
	}

	public void setContactDetail(String contactDetail) {
		this.contactDetail = contactDetail;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}
