package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Doctor generated by hbm2java
 */
public class Doctor extends BaseDomain implements java.io.Serializable {

	public static int OBJECTTYPEID = 11;
	public static String OBJECTTYPESTR = "Doctor";
	
	private int doctorId;
	private int organizationId;
	private int primaryClinicId;
	private String doctorCode;
	private Integer title;
	private Integer showNameType;
	private String firstName;
	private String lastName;
	private String doctorName;
	private String shortName;
	private String userName;
	private String password;
	private int speciality;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date registrationDate;
	private String professionalQualification;
	private String remarks;
	private Integer doctorType;

	public Doctor() {
	}

	public Doctor(int doctorId, int organizationId, int primaryClinicId,
			String doctorCode, String firstName, String doctorName,
			String shortName, int speciality, String professionalQualification,
			int createdBy, Date createdDate, int lastUpdatedBy,
			Date lastUpdatedDate) {
		this.doctorId = doctorId;
		this.organizationId = organizationId;
		this.primaryClinicId = primaryClinicId;
		this.doctorCode = doctorCode;
		this.firstName = firstName;
		this.doctorName = doctorName;
		this.shortName = shortName;
		this.speciality = speciality;
		this.professionalQualification = professionalQualification;
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public Doctor(int doctorId, int organizationId, int primaryClinicId,
			String doctorCode, Integer title, Integer showNameType,
			String firstName, String lastName, String doctorName,
			String shortName, String userName, String password, int speciality,
			Date registrationDate, String professionalQualification,
			String remarks, boolean entityStatus, int createdBy,
			Date createdDate, int lastUpdatedBy, Date lastUpdatedDate) {
		this.doctorId = doctorId;
		this.organizationId = organizationId;
		this.primaryClinicId = primaryClinicId;
		this.doctorCode = doctorCode;
		this.title = title;
		this.showNameType = showNameType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.doctorName = doctorName;
		this.shortName = shortName;
		this.userName = userName;
		this.password = password;
		this.speciality = speciality;
		this.registrationDate = registrationDate;
		this.professionalQualification = professionalQualification;
		this.remarks = remarks;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public int getPrimaryClinicId() {
		return this.primaryClinicId;
	}

	public void setPrimaryClinicId(int primaryClinicId) {
		this.primaryClinicId = primaryClinicId;
	}

	public String getDoctorCode() {
		return this.doctorCode;
	}

	public void setDoctorCode(String doctorCode) {
		this.doctorCode = doctorCode;
	}

	public Integer getTitle() {
		return this.title;
	}

	public void setTitle(Integer title) {
		this.title = title;
	}

	public Integer getShowNameType() {
		return this.showNameType;
	}

	public void setShowNameType(Integer showNameType) {
		this.showNameType = showNameType;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(int speciality) {
		this.speciality = speciality;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public String getProfessionalQualification() {
		return this.professionalQualification;
	}

	public void setProfessionalQualification(String professionalQualification) {
		this.professionalQualification = professionalQualification;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getObjectTypeId() {
		return OBJECTTYPEID;
	}

	public String getObjectTypeStr() {
		return OBJECTTYPESTR;
	}

	public Integer getDoctorType() {
		return doctorType;
	}

	public void setDoctorType(Integer doctorType) {
		this.doctorType = doctorType;
	}
}
