package com.iis.rims.domain;

// Generated Jul 29, 2015 11:30:25 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblLabOrder generated by hbm2java
 */
public class LabOrder extends BaseDomain implements java.io.Serializable {

	private Integer labOrderId;
	private Date orderDate;
	private Integer labCustomerId;
	private int organizationId;
	private int branchId;
	private int visitId;
	private int registrationId;
	private int patientId;
	private String nricFinNumber;
	private String remarks;
	private int orderItemCount;
	private int orderStatus;
	private int orderHl7status;
	private String orderHl7message;
	private Integer orderReportStatus;
	private Integer orderPaymentStatus;
	private String cancellationRemarks;
	private Boolean deleted;

	public LabOrder() {
	}

	public LabOrder(Date orderDate, int branchId, int visitId,
			int registrationId, int patientId, String nricFinNumber,
			int orderItemCount, int orderStatus, int orderHl7status) {
		this.orderDate = orderDate;
		this.branchId = branchId;
		this.visitId = visitId;
		this.registrationId = registrationId;
		this.patientId = patientId;
		this.nricFinNumber = nricFinNumber;
		this.orderItemCount = orderItemCount;
		this.orderStatus = orderStatus;
		this.orderHl7status = orderHl7status;
	}

	public LabOrder(Date orderDate, Integer labCustomerId, int branchId,
			int visitId, int registrationId, int patientId,
			String nricFinNumber, String remarks, int orderItemCount,
			int orderStatus, int orderHl7status, String orderHl7message,
			Integer orderReportStatus, Integer orderPaymentStatus,
			String cancellationRemarks, Boolean deleted) {
		this.orderDate = orderDate;
		this.labCustomerId = labCustomerId;
		this.branchId = branchId;
		this.visitId = visitId;
		this.registrationId = registrationId;
		this.patientId = patientId;
		this.nricFinNumber = nricFinNumber;
		this.remarks = remarks;
		this.orderItemCount = orderItemCount;
		this.orderStatus = orderStatus;
		this.orderHl7status = orderHl7status;
		this.orderHl7message = orderHl7message;
		this.orderReportStatus = orderReportStatus;
		this.orderPaymentStatus = orderPaymentStatus;
		this.cancellationRemarks = cancellationRemarks;
		this.deleted = deleted;
	}

	public Integer getLabOrderId() {
		return this.labOrderId;
	}

	public void setLabOrderId(Integer labOrderId) {
		this.labOrderId = labOrderId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Integer getLabCustomerId() {
		return this.labCustomerId;
	}

	public void setLabCustomerId(Integer labCustomerId) {
		this.labCustomerId = labCustomerId;
	}

	public int getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getVisitId() {
		return this.visitId;
	}

	public void setVisitId(int visitId) {
		this.visitId = visitId;
	}

	public int getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(int registrationId) {
		this.registrationId = registrationId;
	}

	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	public String getNricFinNumber() {
		return this.nricFinNumber;
	}

	public void setNricFinNumber(String nricFinNumber) {
		this.nricFinNumber = nricFinNumber;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getOrderItemCount() {
		return this.orderItemCount;
	}

	public void setOrderItemCount(int orderItemCount) {
		this.orderItemCount = orderItemCount;
	}

	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	public int getOrderHl7status() {
		return this.orderHl7status;
	}

	public void setOrderHl7status(int orderHl7status) {
		this.orderHl7status = orderHl7status;
	}

	public String getOrderHl7message() {
		return this.orderHl7message;
	}

	public void setOrderHl7message(String orderHl7message) {
		this.orderHl7message = orderHl7message;
	}

	public Integer getOrderReportStatus() {
		return this.orderReportStatus;
	}

	public void setOrderReportStatus(Integer orderReportStatus) {
		this.orderReportStatus = orderReportStatus;
	}

	public Integer getOrderPaymentStatus() {
		return this.orderPaymentStatus;
	}

	public void setOrderPaymentStatus(Integer orderPaymentStatus) {
		this.orderPaymentStatus = orderPaymentStatus;
	}

	public String getCancellationRemarks() {
		return this.cancellationRemarks;
	}

	public void setCancellationRemarks(String cancellationRemarks) {
		this.cancellationRemarks = cancellationRemarks;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	@Override
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
}
