package com.iis.rims.domain;

// Generated Sep 9, 2015 7:39:17 PM by Hibernate Tools 4.0.0


/**
 * TblLabRttestCode generated by hbm2java
 */
public class LabRtTestCode extends BaseDomain implements java.io.Serializable {

}
