package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LookupHeader generated by hbm2java
 */
public class LookupHeader extends BaseDomain implements java.io.Serializable {

	public static int OBJECTTYPE = 13;
	public static String OBJECTTYPESTR = "LookupHeader";
	
	private int lookupHeaderId;
	private int organizationId;
	private String lookupName;
	private String lookupDescription;

	public LookupHeader() {
	}

	public LookupHeader(int lookupHeaderId, int organizationId,
			String lookupName, boolean entityStatus, int createdBy,
			Date createdDate, int lastUpdatedBy, Date lastUpdatedDate) {
		this.lookupHeaderId = lookupHeaderId;
		this.organizationId = organizationId;
		this.lookupName = lookupName;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public LookupHeader(int lookupHeaderId, int organizationId,
			String lookupName, String lookupDescription, boolean entityStatus,
			int createdBy, Date createdDate, int lastUpdatedBy,
			Date lastUpdatedDate) {
		this.lookupHeaderId = lookupHeaderId;
		this.organizationId = organizationId;
		this.lookupName = lookupName;
		this.lookupDescription = lookupDescription;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public int getLookupHeaderId() {
		return this.lookupHeaderId;
	}

	public void setLookupHeaderId(int lookupHeaderId) {
		this.lookupHeaderId = lookupHeaderId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public String getLookupName() {
		return this.lookupName;
	}

	public void setLookupName(String lookupName) {
		this.lookupName = lookupName;
	}

	public String getLookupDescription() {
		return this.lookupDescription;
	}

	public void setLookupDescription(String lookupDescription) {
		this.lookupDescription = lookupDescription;
	}
}
