package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Patient generated by hbm2java
 */
public class Patient extends BaseDomain {

	public static int OBJECTTYPEID = 12;
	public static String OBJECTTYPESTR = "Patient";
	
	private int patientId;
	private int organizationId;
	private Integer identificationType;
	private String nricFinNumber;
	private String firstName;
	private String lastName;
	private String patientName;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date dateOfBirth;
	private int gender;
	private int maritalStatus;
	private int educationLevel;
	private int occupation;
	private int race;
	private int language;
	private int numberOfChildren;
	private Integer nationality;
	private String allergy;
	private String additionalRemarks;
	private Integer referringCardType;
	private String referringCardNumber;
	private Date referringRegisteredDate;
	private Integer branchId;
	private Integer patientStatus;
	private Integer religion;
	private Integer patientCategory;
	private Integer patientPhysicalStatus;
	
	private Integer nricTypeId;
	private Integer infectionStatusId;	
	private BigDecimal wheelchairWeight;
	
	private Boolean sapb1Posted;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date sapb1PostedDate;
	private String sapb1ReferenceRemarks;
	private Integer smokingHabit;
	
	private Double patientHeight;
	
	public Patient() {
	}

	public Patient(int patientId, int organizationId,
			String nricFinNumber, String firstName, String patientName,
			Date dateOfBirth, int gender, int maritalStatus,
			int educationLevel, int occupation, int race, int numberOfChildren) {
		this.patientId = patientId;
		this.organizationId = organizationId;
		this.nricFinNumber = nricFinNumber;
		this.firstName = firstName;
		this.patientName = patientName;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.educationLevel = educationLevel;
		this.occupation = occupation;
		this.race = race;
		this.numberOfChildren = numberOfChildren;
	}

	public Patient(int patientId, int organizationId,
			Integer identificationType, String nricFinNumber,
			String firstName, String lastName, String patientName,
			Date dateOfBirth, int gender, int maritalStatus,
			int educationLevel, int occupation, int race, int language,
			int numberOfChildren, Integer nationality, String allergy,
			String additionalRemarks, Integer referringCardType,
			String referringCardNumber, Date referringRegisteredDate,
			boolean entityStatus, int createdBy, Date createdDate,
			int lastUpdatedBy, Date lastUpdatedDate) {
		this.patientId = patientId;
		this.organizationId = organizationId;
		this.identificationType = identificationType;
		this.nricFinNumber = nricFinNumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.patientName = patientName;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.educationLevel = educationLevel;
		this.occupation = occupation;
		this.race = race;
		this.language = language;
		this.numberOfChildren = numberOfChildren;
		this.nationality = nationality;
		this.allergy = allergy;
		this.additionalRemarks = additionalRemarks;
		this.referringCardType = referringCardType;
		this.referringCardNumber = referringCardNumber;
		this.referringRegisteredDate = referringRegisteredDate;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public Integer getIdentificationType() {
		return this.identificationType;
	}

	public void setIdentificationType(Integer identificationType) {
		this.identificationType = identificationType;
	}

	public String getNricFinNumber() {
		return this.nricFinNumber;
	}

	public void setNricFinNumber(String nricFinNumber) {
		this.nricFinNumber = nricFinNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(int maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public int getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(int educationLevel) {
		this.educationLevel = educationLevel;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getRace() {
		return this.race;
	}

	public void setRace(int race) {
		this.race = race;
	}

	public Integer getLanguage() {
		return this.language;
	}

	public void setLanguage(Integer language) {
		this.language = language;
	}

	public int getNumberOfChildren() {
		return this.numberOfChildren;
	}

	public void setNumberOfChildren(int numberOfChildren) {
		this.numberOfChildren = numberOfChildren;
	}

	public Integer getNationality() {
		return this.nationality;
	}

	public void setNationality(Integer nationality) {
		this.nationality = nationality;
	}

	public String getAllergy() {
		return this.allergy;
	}

	public void setAllergy(String allergy) {
		this.allergy = allergy;
	}

	public String getAdditionalRemarks() {
		return this.additionalRemarks;
	}

	public void setAdditionalRemarks(String additionalRemarks) {
		this.additionalRemarks = additionalRemarks;
	}

	public Integer getReferringCardType() {
		return this.referringCardType;
	}

	public void setReferringCardType(Integer referringCardType) {
		this.referringCardType = referringCardType;
	}

	public String getReferringCardNumber() {
		return this.referringCardNumber;
	}

	public void setReferringCardNumber(String referringCardNumber) {
		this.referringCardNumber = referringCardNumber;
	}

	public Date getReferringRegisteredDate() {
		return this.referringRegisteredDate;
	}

	public void setReferringRegisteredDate(Date referringRegisteredDate) {
		this.referringRegisteredDate = referringRegisteredDate;
	}

	public int getObjectTypeId() {
		return OBJECTTYPEID;
	}

	public String getObjectTypeStr() {
		return OBJECTTYPESTR;
	}
	
	public Integer getBranchId() {
		return branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}
	
	public Integer getPatientStatus() {
		return patientStatus;
	}

	public void setPatientStatus(Integer patientStatus) {
		this.patientStatus = patientStatus;
	}

	public Integer getReligion() {
		return religion;
	}

	public void setReligion(Integer religion) {
		this.religion = religion;
	}

	public Integer getPatientCategory() {
		return patientCategory;
	}

	public void setPatientCategory(Integer patientCategory) {
		this.patientCategory = patientCategory;
	}

	public Integer getPatientPhysicalStatus() {
		return patientPhysicalStatus;
	}

	public void setPatientPhysicalStatus(Integer patientPhysicalStatus) {
		this.patientPhysicalStatus = patientPhysicalStatus;
	}


	public Integer getNricTypeId() {
		return nricTypeId;
	}

	public void setNricTypeId(Integer nricTypeId) {
		this.nricTypeId = nricTypeId;
	}

	public Integer getInfectionStatusId() {
		return infectionStatusId;
	}

	public void setInfectionStatusId(Integer infectionStatusId) {
		this.infectionStatusId = infectionStatusId;
	}

	public BigDecimal getWheelchairWeight() {
		return wheelchairWeight;
	}

	public void setWheelchairWeight(BigDecimal wheelchairWeight) {
		this.wheelchairWeight = wheelchairWeight;
	}

	public Boolean getSapb1Posted() {
		return sapb1Posted;
	}

	public void setSapb1Posted(Boolean sAPB1Posted) {
		sapb1Posted = sAPB1Posted;
	}

	public Date getSapb1PostedDate() {
		return sapb1PostedDate;
	}

	public void setSapb1PostedDate(Date sAPB1PostedDate) {
		sapb1PostedDate = sAPB1PostedDate;
	}

	public String getSapb1ReferenceRemarks() {
		return sapb1ReferenceRemarks;
	}

	public void setSapb1ReferenceRemarks(String sapb1ReferenceRemarks) {
		this.sapb1ReferenceRemarks = sapb1ReferenceRemarks;
	}

	public Integer getSmokingHabit() {
		return smokingHabit;
	}

	public void setSmokingHabit(Integer smokingHabit) {
		this.smokingHabit = smokingHabit;
	}

	public void setLanguage(int language) {
		this.language = language;
	}

	public Double getPatientHeight() {
		return patientHeight;
	}

	public void setPatientHeight(Double patientHeight) {
		this.patientHeight = patientHeight;
	}
}
