package com.iis.rims.domain;

// Generated Jun 20, 2013 11:25:34 PM by Hibernate Tools 4.0.0

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * RunningNumberSet generated by hbm2java
 */
@JsonIgnoreProperties(value = {})
public class RunningNumberSet extends BaseDomain implements java.io.Serializable {

	private Integer runningNumberSetId;
	private int organizationId;
	private int branchId;
	private String runningNumberType;
	private Boolean isCountryCodeSet;
	private Boolean isOrganizationCodeSet;
	private Boolean isBranchCodeSet;
	private Boolean isServiceClassCodeSet;
	private Boolean isServiceCodeSet;
	private Boolean isServicePrefixCodeSet;
	private Boolean isYearSet;
	private Boolean isMonthSet;
	private Boolean isDateSet;
	private Boolean isStartTimeSet;
	private Integer startRunningNumber;
	private Boolean setStartRunningNumber;
	private Integer startDigits;
	private Boolean isDaySet;
	private Boolean isSeparatorCharSet;
	private Boolean isYearRollSet;
	private Boolean isOrganizationBased;
	private Boolean isBranchBased;
	private String monthFormat;
	private Boolean isMonthRollSet;

	public RunningNumberSet() {
	}

	public RunningNumberSet(int organizationId, int branchId,
			boolean entityStatus, int createdBy, Date createdDate,
			int lastUpdatedBy, Date lastUpdatedDate) {
		this.organizationId = organizationId;
		this.branchId = branchId;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public RunningNumberSet(int organizationId, int branchId, String runningNumberType, 
			Boolean isCountryCodeSet, Boolean isOrganizationCodeSet,
			Boolean isBranchCodeSet, Boolean isServiceClassCodeSet,
			Boolean isServiceCodeSet, Boolean isYearSet, Boolean isMonthSet,
			Boolean isDateSet, Boolean isStartTimeSet,
			Boolean setStartRunningNumber, Integer startDigits,
			Boolean isSeparatorCharSet, Boolean isYearRollSet,
			boolean entityStatus, int createdBy, Date createdDate,
			int lastUpdatedBy, Date lastUpdatedDate) {
		this.organizationId = organizationId;
		this.branchId = branchId;
		this.runningNumberType = runningNumberType;
		this.isCountryCodeSet = isCountryCodeSet;
		this.isOrganizationCodeSet = isOrganizationCodeSet;
		this.isBranchCodeSet = isBranchCodeSet;
		this.isServiceClassCodeSet = isServiceClassCodeSet;
		this.isServiceCodeSet = isServiceCodeSet;
		this.isYearSet = isYearSet;
		this.isMonthSet = isMonthSet;
		this.isDateSet = isDateSet;
		this.isStartTimeSet = isStartTimeSet;
		this.setStartRunningNumber = setStartRunningNumber;
		this.startDigits = startDigits;
		this.isSeparatorCharSet = isSeparatorCharSet;
		this.isYearRollSet = isYearRollSet;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public Integer getRunningNumberSetId() {
		return this.runningNumberSetId;
	}

	public void setRunningNumberSetId(Integer runningNumberSetId) {
		this.runningNumberSetId = runningNumberSetId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public Boolean getIsOrganizationBased() {
		return isOrganizationBased;
	}

	public void setIsOrganizationBased(Boolean isOrganizationBased) {
		this.isOrganizationBased = isOrganizationBased;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public Boolean getIsBranchBased() {
		return isBranchBased;
	}

	public void setIsBranchBased(Boolean isBranchBased) {
		this.isBranchBased = isBranchBased;
	}

	public Boolean getIsCountryCodeSet() {
		return this.isCountryCodeSet;
	}

	public String getRunningNumberType() {
		return runningNumberType;
	}

	public void setRunningNumberType(String runningNumberType) {
		this.runningNumberType = runningNumberType;
	}

	public void setIsCountryCodeSet(Boolean isCountryCodeSet) {
		this.isCountryCodeSet = isCountryCodeSet;
	}

	public Boolean getIsOrganizationCodeSet() {
		return this.isOrganizationCodeSet;
	}

	public void setIsOrganizationCodeSet(Boolean isOrganizationCodeSet) {
		this.isOrganizationCodeSet = isOrganizationCodeSet;
	}

	public Boolean getIsBranchCodeSet() {
		return this.isBranchCodeSet;
	}

	public void setIsBranchCodeSet(Boolean isBranchCodeSet) {
		this.isBranchCodeSet = isBranchCodeSet;
	}

	public Boolean getIsServiceClassCodeSet() {
		return this.isServiceClassCodeSet;
	}

	public void setIsServiceClassCodeSet(Boolean isServiceClassCodeSet) {
		this.isServiceClassCodeSet = isServiceClassCodeSet;
	}

	public Boolean getIsServiceCodeSet() {
		return this.isServiceCodeSet;
	}

	public void setIsServiceCodeSet(Boolean isServiceCodeSet) {
		this.isServiceCodeSet = isServiceCodeSet;
	}
	
	public Boolean getIsServicePrefixCodeSet() {
		return this.isServicePrefixCodeSet;
	}
	
	public void setIsServicePrefixCodeSet(Boolean isServicePrefixCodeSet) {
		this.isServicePrefixCodeSet = isServicePrefixCodeSet;
	}

	public Boolean getIsYearSet() {
		return this.isYearSet;
	}

	public void setIsYearSet(Boolean isYearSet) {
		this.isYearSet = isYearSet;
	}

	public Boolean getIsMonthSet() {
		return this.isMonthSet;
	}

	public void setIsMonthSet(Boolean isMonthSet) {
		this.isMonthSet = isMonthSet;
	}

	public Boolean getIsDateSet() {
		return this.isDateSet;
	}

	public void setIsDateSet(Boolean isDateSet) {
		this.isDateSet = isDateSet;
	}

	public Boolean getIsStartTimeSet() {
		return this.isStartTimeSet;
	}

	public void setIsStartTimeSet(Boolean isStartTimeSet) {
		this.isStartTimeSet = isStartTimeSet;
	}

	public Boolean getSetStartRunningNumber() {
		return this.setStartRunningNumber;
	}

	public void setSetStartRunningNumber(Boolean setStartRunningNumber) {
		this.setStartRunningNumber = setStartRunningNumber;
	}

	public Integer getStartDigits() {
		return this.startDigits;
	}

	public Integer getStartRunningNumber() {
		return startRunningNumber;
	}

	public void setStartRunningNumber(Integer startRunningNumber) {
		this.startRunningNumber = startRunningNumber;
	}

	public void setStartDigits(Integer startDigits) {
		this.startDigits = startDigits;
	}

	public Boolean getIsSeparatorCharSet() {
		return this.isSeparatorCharSet;
	}

	public Boolean getIsDaySet() {
		return isDaySet;
	}

	public void setIsDaySet(Boolean isDaySet) {
		this.isDaySet = isDaySet;
	}

	public void setIsSeparatorCharSet(Boolean isSeparatorCharSet) {
		this.isSeparatorCharSet = isSeparatorCharSet;
	}

	public Boolean getIsYearRollSet() {
		return this.isYearRollSet;
	}

	public void setIsYearRollSet(Boolean isYearRollSet) {
		this.isYearRollSet = isYearRollSet;
	}

	public String getMonthFormat() {
		return monthFormat;
	}

	public void setMonthFormat(String monthFormat) {
		this.monthFormat = monthFormat;
	}

	public Boolean getIsMonthRollSet() {
		return isMonthRollSet;
	}

	public void setIsMonthRollSet(Boolean isMonthRollSet) {
		this.isMonthRollSet = isMonthRollSet;
	}
}
