package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SystemUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class SystemUser extends BaseDomain implements java.io.Serializable {

	/**
	 * 
	 */
	public static int OBJECTTYPEID = 16;
	public static String OBJECTTYPESTR = "SystemUser";
	
	private int userId;
	private int organizationId;
	private int defaultBranchId;
	private Integer userType;
	private String loginName;
	private Boolean hasAdminRole;
	private Boolean managementUser;
	private String password;
	private String employeeNo;
	private String nricfinnumber;
	private String displayName;
	private String firstName;
	private String lastName;
	private String email;
	private String officeTel;
	private String mobile;
	private int userStatus;
	private String userStatusRemark;
	private int designation;

	public SystemUser() {
	}

	public SystemUser(int userId, int organizationId, int defaultBranchId) {
		this.userId = userId;
		this.organizationId = organizationId;
		this.defaultBranchId = defaultBranchId;
	}

	public SystemUser(int userId, int organizationId, int defaultBranchId,
			Integer userType, String loginName, Boolean hasAdminRole,
			Boolean managementUser, String password, String employeeNo,
			String nricfinnumber, String displayName, String firstName,
			String lastName, String email, String officeTel, String mobile,
			int userStatus, String userStatusRemark, boolean entityStatus,
			Integer createdBy, Date createdDate, Integer lastUpdatedBy,
			Date lastUpdatedDate, int designation) {
		this.userId = userId;
		this.organizationId = organizationId;
		this.defaultBranchId = defaultBranchId;
		this.userType = userType;
		this.loginName = loginName;
		this.hasAdminRole = hasAdminRole;
		this.managementUser = managementUser;
		this.password = password;
		this.employeeNo = employeeNo;
		this.nricfinnumber = nricfinnumber;
		this.displayName = displayName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.officeTel = officeTel;
		this.mobile = mobile;
		this.userStatus = userStatus;
		this.userStatusRemark = userStatusRemark;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public int getDefaultBranchId() {
		return this.defaultBranchId;
	}

	public void setDefaultBranchId(int defaultBranchId) {
		this.defaultBranchId = defaultBranchId;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public Boolean getHasAdminRole() {
		return this.hasAdminRole != null ? this.hasAdminRole : false;
	}

	public void setHasAdminRole(Boolean hasAdminRole) {
		this.hasAdminRole = hasAdminRole;
	}

	public Boolean getManagementUser() {
		return this.managementUser != null ? this.managementUser : false;
	}

	public void setManagementUser(Boolean managementUser) {
		this.managementUser = managementUser;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	public String getNricfinnumber() {
		return this.nricfinnumber;
	}

	public void setNricfinnumber(String nricfinnumber) {
		this.nricfinnumber = nricfinnumber;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getOfficeTel() {
		return this.officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public int getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserStatusRemark() {
		return this.userStatusRemark;
	}

	public void setUserStatusRemark(String userStatusRemark) {
		this.userStatusRemark = userStatusRemark;
	}

	public int getObjectTypeId() {
		return OBJECTTYPEID;
	}

	public String getObjectTypeStr() {
		return OBJECTTYPESTR;
	}
	
	public int getDesignation() {
		return this.designation;
	}

	public void setDesignation(int designation) {
		this.designation = designation;
	}
}
