package com.iis.rims.domain;
// default package
// Generated May 19, 2013 1:12:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Visit generated by hbm2java
 */
public class Visit extends BaseDomain implements java.io.Serializable {

	public static int OBJECTTYPE = 32;
	public static String OBJECTTYPESTR = "Visit";
	
	private int visitId;
	private int registrationId;
	private int branchId;
	private int serviceClassId;
	private Integer equipmentDetailId;
	private String equipmentDetailName;
	private int visitType;
	private String visitNumber;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date visitDate;
	private boolean newOrBhb;
	private int ageYears;
	private int ageMonths;
	private int ageDays;
	private Integer referringCustomerId;
	private Integer referringBillToId;
	private Integer referringDoctorId;
	private String referringClinicName;
	private String referringDoctorName;
	private int billToType;
	private int billToId;
	private String remarks;
	private String cancellationRemarks;
	private int visitStatus;

	private Integer appointmentId;
	
	private Integer medicalSocialWorkerId;
	private String medicalSocialWorkerName;
	
	private Integer PreviousDialysisCentreId;
	private String PreviousDialysisCentreName;
	private boolean inPatient = false;
	
	public Visit() {
	}

	public Visit(int visitId, int registrationId, int branchId,
			int serviceClassId, int visitType, String visitNumber,
			Date visitDate, boolean newOrBhb, int ageYears, int ageMonths,
			int ageDays, String referringClinicName,
			String referringDoctorName, int billToType, int billToId,
			int visitStatus, boolean entityStatus, int createdBy,
			Date createdDate, int lastUpdatedBy, Date lastUpdatedDate) {
		this.visitId = visitId;
		this.registrationId = registrationId;
		this.branchId = branchId;
		this.serviceClassId = serviceClassId;
		this.visitType = visitType;
		this.visitNumber = visitNumber;
		this.visitDate = visitDate;
		this.newOrBhb = newOrBhb;
		this.ageYears = ageYears;
		this.ageMonths = ageMonths;
		this.ageDays = ageDays;
		this.referringClinicName = referringClinicName;
		this.referringDoctorName = referringDoctorName;
		this.billToType = billToType;
		this.billToId = billToId;
		this.visitStatus = visitStatus;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
	}

	public Visit(int visitId, int registrationId, int branchId,
			int serviceClassId, int visitType, String visitNumber,
			Date visitDate, boolean newOrBhb, int ageYears, int ageMonths,
			int ageDays, Integer referringCustomerId,
			Integer referringBillToId, Integer referringDoctorId,
			String referringClinicName, String referringDoctorName,
			int billToType, int billToId, String remarks, int visitStatus,
			boolean entityStatus, int createdBy, Date createdDate,
			int lastUpdatedBy, Date lastUpdatedDate, Integer equipmentDetailId,
			String equipmentDetailName) {
		this.visitId = visitId;
		this.registrationId = registrationId;
		this.branchId = branchId;
		this.serviceClassId = serviceClassId;
		this.visitType = visitType;
		this.visitNumber = visitNumber;
		this.visitDate = visitDate;
		this.newOrBhb = newOrBhb;
		this.ageYears = ageYears;
		this.ageMonths = ageMonths;
		this.ageDays = ageDays;
		this.referringCustomerId = referringCustomerId;
		this.referringBillToId = referringBillToId;
		this.referringDoctorId = referringDoctorId;
		this.referringClinicName = referringClinicName;
		this.referringDoctorName = referringDoctorName;
		this.billToType = billToType;
		this.billToId = billToId;
		this.remarks = remarks;
		this.visitStatus = visitStatus;
		this.setEntityStatus(entityStatus);
		this.setCreatedBy(createdBy);
		this.setCreatedDate(createdDate);
		this.setLastUpdatedBy(lastUpdatedBy);
		this.setLastUpdatedDate(lastUpdatedDate);
		this.equipmentDetailId = equipmentDetailId;
		this.equipmentDetailName = equipmentDetailName;
	}
	
	
	public Visit(Visit visitEnt) {
		this.visitId = visitEnt.getVisitId();
		this.registrationId = visitEnt.getRegistrationId();
		this.branchId = visitEnt.getBranchId();
		this.serviceClassId = visitEnt.getServiceClassId();
		this.visitType = visitEnt.getVisitType();
		this.visitNumber = visitEnt.getVisitNumber();
		this.visitDate = visitEnt.getVisitDate();
		this.newOrBhb = visitEnt.isNewOrBhb();
		this.ageYears = visitEnt.getAgeYears();
		this.ageMonths = visitEnt.getAgeMonths();
		this.ageDays = visitEnt.getAgeDays();
		this.referringCustomerId = visitEnt.getReferringCustomerId();
		this.referringBillToId = visitEnt.getReferringBillToId();
		this.referringDoctorId = visitEnt.getReferringDoctorId();
		this.referringClinicName = visitEnt.getReferringClinicName();
		this.referringDoctorName = visitEnt.getReferringDoctorName();
		this.billToType = visitEnt.getBillToType();
		this.billToId = visitEnt.getBillToId();
		this.remarks = visitEnt.getRemarks();
		this.visitStatus = visitEnt.getVisitStatus();
		this.setEntityStatus(visitEnt.isEntityStatus());
		this.setCreatedBy(visitEnt.getCreatedBy());
		this.setCreatedDate(visitEnt.getCreatedDate());
		this.setLastUpdatedBy(visitEnt.getLastUpdatedBy());
		this.setLastUpdatedDate(visitEnt.getLastUpdatedDate());
		this.equipmentDetailId = visitEnt.getEquipmentDetailId();
		this.equipmentDetailName = visitEnt.getEquipmentDetailName();
	}	

	public int getVisitId() {
		return this.visitId;
	}

	public void setVisitId(int visitId) {
		this.visitId = visitId;
	}

	public int getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(int registrationId) {
		this.registrationId = registrationId;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getServiceClassId() {
		return this.serviceClassId;
	}

	public void setServiceClassId(int serviceClassId) {
		this.serviceClassId = serviceClassId;
	}

	public int getVisitType() {
		return this.visitType;
	}

	public Integer getEquipmentDetailId() {
		return equipmentDetailId;
	}

	public void setEquipmentDetailId(Integer equipmentDetailId) {
		this.equipmentDetailId = equipmentDetailId;
	}

	public void setVisitType(int visitType) {
		this.visitType = visitType;
	}

	public String getVisitNumber() {
		return this.visitNumber;
	}

	public void setVisitNumber(String visitNumber) {
		this.visitNumber = visitNumber;
	}

	public Date getVisitDate() {
		return this.visitDate;
	}

	public void setVisitDate(Date visitDate) {
		this.visitDate = visitDate;
	}

	public boolean isNewOrBhb() {
		return this.newOrBhb;
	}

	public void setNewOrBhb(boolean newOrBhb) {
		this.newOrBhb = newOrBhb;
	}

	public int getAgeYears() {
		return this.ageYears;
	}

	public void setAgeYears(int ageYears) {
		this.ageYears = ageYears;
	}

	public int getAgeMonths() {
		return this.ageMonths;
	}

	public void setAgeMonths(int ageMonths) {
		this.ageMonths = ageMonths;
	}

	public int getAgeDays() {
		return this.ageDays;
	}

	public void setAgeDays(int ageDays) {
		this.ageDays = ageDays;
	}

	public Integer getReferringCustomerId() {
		return this.referringCustomerId;
	}

	public void setReferringCustomerId(Integer referringCustomerId) {
		this.referringCustomerId = referringCustomerId;
	}

	public Integer getReferringBillToId() {
		return this.referringBillToId;
	}

	public void setReferringBillToId(Integer referringBillToId) {
		this.referringBillToId = referringBillToId;
	}

	public Integer getReferringDoctorId() {
		return this.referringDoctorId;
	}

	public void setReferringDoctorId(Integer referringDoctorId) {
		this.referringDoctorId = referringDoctorId;
	}

	public String getReferringClinicName() {
		return this.referringClinicName;
	}

	public void setReferringClinicName(String referringClinicName) {
		this.referringClinicName = referringClinicName;
	}

	public String getReferringDoctorName() {
		return this.referringDoctorName;
	}

	public void setReferringDoctorName(String referringDoctorName) {
		this.referringDoctorName = referringDoctorName;
	}

	public int getBillToType() {
		return this.billToType;
	}

	public void setBillToType(int billToType) {
		this.billToType = billToType;
	}

	public int getBillToId() {
		return this.billToId;
	}

	public void setBillToId(int billToId) {
		this.billToId = billToId;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCancellationRemarks() {
		return cancellationRemarks;
	}

	public void setCancellationRemarks(String cancellationRemarks) {
		this.cancellationRemarks = cancellationRemarks;
	}

	public int getVisitStatus() {
		return this.visitStatus;
	}

	public void setVisitStatus(int visitStatus) {
		this.visitStatus = visitStatus;
	}

	public String getEquipmentDetailName() {
		return equipmentDetailName;
	}

	public void setEquipmentDetailName(String equipmentDetailName) {
		this.equipmentDetailName = equipmentDetailName;
	}

	public Integer getAppointmentId() {
		return appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	public Integer getMedicalSocialWorkerId() {
		return medicalSocialWorkerId;
	}

	public void setMedicalSocialWorkerId(Integer medicalSocialWorkerId) {
		this.medicalSocialWorkerId = medicalSocialWorkerId;
	}

	public String getMedicalSocialWorkerName() {
		return medicalSocialWorkerName;
	}

	public void setMedicalSocialWorkerName(String medicalSocialWorkerName) {
		this.medicalSocialWorkerName = medicalSocialWorkerName;
	}

	public Integer getPreviousDialysisCentreId() {
		return PreviousDialysisCentreId;
	}

	public void setPreviousDialysisCentreId(Integer previousDialysisCentreId) {
		PreviousDialysisCentreId = previousDialysisCentreId;
	}

	public String getPreviousDialysisCentreName() {
		return PreviousDialysisCentreName;
	}

	public void setPreviousDialysisCentreName(String previousDialysisCentreName) {
		PreviousDialysisCentreName = previousDialysisCentreName;
	}

	public boolean isInPatient() {
		return inPatient;
	}

	public void setInPatient(boolean inPatient) {
		this.inPatient = inPatient;
	}
}
